### ISSUE TITLE
Missing information on mockReturnValue, mockResolvedValue etc

### ISSUE THREAD

**Issue by toeryn** [sapegin/jest-cheat-sheet#11]
Use your cheat sheet from time to time, would love to see some information on mockReturnValue/mockResolveValue etc.

I took the liberty of writing some info about them locally, but I do not have the permissions to submit a PR

I added the following section (under mocks):

### Returning, resolving and rejecting values

Your mocks can return values:

```js
const callback = jest.fn().mockReturnValue(true);
const callbackOnce = jest.fn().mockReturnValueOnce(true);
```

Or resolve values:

```js
const promise = jest.fn().mockResolvedValue(true);
const promiseOnce = jest.fn().mockResolvedValueOnce(true);
```

They can even reject values:

```js
const failedPromise = jest.fn().mockRejectedValue("Error");
const failedPromiseOnce = jest.fn().mockRejectedValueOnce("Error");
```

You can even combine these:

```js
const callback = jest.fn()
  .mockReturnValueOnce(false)
  .mockReturnValue(true);

// ->
//  call 1: false
//  call 2+: true
```

**Comment by sapegin** [comment]
Looks good, thanks!

> I do not have the permissions to submit a PR

You don't need permission for that. The "edit" button here should create a fork, and you'll be able to open a pull request:

![CleanShot 2020-06-09 at 17 58 16@2x](https://user-images.githubusercontent.com/70067/84171226-e00e7f80-aa7a-11ea-9462-8e4938089463.png)

**Comment by toeryn** [comment]
Thanks, always work through CLI, had assumed if CLI would not give permission then the front end would be the same!

PR -> https://github.com/sapegin/jest-cheat-sheet/pull/12
